cmake_minimum_required(VERSION 3.18 FATAL_ERROR)

set(OPENCFLITE_VERSION "1.0")
set(OPENCFLITE_LANGUAGES )
set(OPENCFLITE_CODESIGNING )
set(SW_VERS "")
set(UNAME_M "")
set(SYSROOT "/")

if (APPLE)
    list(APPEND OPENCFLITE_LANGUAGES "C")
    list(APPEND OPENCFLITE_LANGUAGES "CXX")
    list(APPEND OPENCFLITE_LANGUAGES "OBJC")
    list(APPEND OPENCFLITE_LANGUAGES "OBJCXX")
    execute_process(COMMAND sw_vers -productVersion OUTPUT_VARIABLE SW_VERS ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
    execute_process(COMMAND uname -m OUTPUT_VARIABLE UNAME_M ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
    if ("${CMAKE_GENERATOR}" MATCHES "Xcode")
        if (NOT "$ENV{SYSROOT}" STREQUAL "")
            set(SYSROOT "$ENV{SYSROOT}")
        else()
            execute_process(COMMAND xcodebuild -version -sdk macosx Path OUTPUT_VARIABLE SYSROOT ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
        endif()
        if (NOT EXISTS "${SYSROOT}")
            message(FATAL_ERROR "SYSROOT does not exist!")
        endif()
        set(CMAKE_OSX_SYSROOT "${SYSROOT}" CACHE STRING "CMAKE_OSX_SYSROOT" FORCE)
        if ("${CMAKE_OSX_ARCHITECTURES}" STREQUAL "")
            if ("${UNAME_M}" MATCHES "arm")
                set(CMAKE_OSX_ARCHITECTURES "arm64" CACHE STRING "CMAKE_OSX_ARCHITECTURES" FORCE)
            else()
                set(CMAKE_OSX_ARCHITECTURES "$(ARCHS_STANDARD)" CACHE STRING "CMAKE_OSX_ARCHITECTURES" FORCE)
            endif()
        endif()
    endif()
    execute_process(COMMAND security find-identity -v -p codesigning OUTPUT_VARIABLE SECURITY_FOUND_IDENTITY ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
    set(PATTERN " ")
    foreach(IDX RANGE 1 40 1)
        string(APPEND PATTERN "[a-fA-F0-9]")
    endforeach()
    string(APPEND PATTERN " ")
    string(REGEX MATCH "${PATTERN}" IDENTITY "${SECURITY_FOUND_IDENTITY}")
    if (NOT "${IDENTITY}" STREQUAL "")
        string(STRIP "${IDENTITY}" OPENCFLITE_CODESIGNING)
    endif()
else()
    if (NOT (WINDOWS OR APPLE OR ANDROID))
        execute_process(COMMAND uname -m OUTPUT_VARIABLE UNAME_M ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
    endif()
    list(APPEND OPENCFLITE_LANGUAGES "C")
    list(APPEND OPENCFLITE_LANGUAGES "CXX")
    if (MINGW)
        list(APPEND OPENCFLITE_LANGUAGES "RC")
    endif()
endif()

macro(set_option var default type docstring)
	  if (("${type}" STREQUAL "STRING" AND "${var}" STREQUAL "") OR NOT DEFINED ${var})
		    set(${var} ${default})
	  endif()
	  set(${var} ${${var}} CACHE ${type} ${docstring} FORCE)
endmacro()

if ("${CMAKE_GENERATOR}" MATCHES "Xcode" AND NOT "${SW_VERS}" STREQUAL "")
    string(REPLACE "." ";" SW_VERS_MAJOR "${SW_VERS}")
    list(POP_FRONT SW_VERS_MAJOR SW_VERS_HEAD)
    set(SW_VERS "${SW_VERS_HEAD}")
    set_option(CMAKE_OSX_DEPLOYMENT_TARGET "${SW_VERS}" STRING "Choose the minimum MacOS deployment version")
endif()
set_option(CMAKE_BUILD_TYPE "Debug" STRING "Choose the type of build config variant (\"Debug\" or \"Release\")")
set_option(OPENCFLITE_LINKAGE "STATIC" STRING "Choose the type of library linkage for the libopencflite target (\"STATIC\" or \"SHARED\")")
set_option(OPENCFLITE_BINARIES "OFF" STRING "Whether or not to build the opencflite executable targets (\"ON\" or \"OFF\")")
set_option(OPENCFLITE_TESTING "OFF" STRING "Whether or not to run unit tests (\"ON\" or \"OFF\")")

project(opencfliteproject VERSION ${OPENCFLITE_VERSION} LANGUAGES ${OPENCFLITE_LANGUAGES})

list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/cmake)

set(CMAKE_SHARED_LIBRARY_PREFIX "")
set(CMAKE_STATIC_LIBRARY_PREFIX "")
if (NOT "${CMAKE_BUILD_TYPE}" STREQUAL "Release")
    set(CMAKE_DEBUG_POSTFIX "${CMAKE_BUILD_TYPE}")
endif()

set(OPENCFLITE_DEF )
list(APPEND OPENCFLITE_DEF CF_BUILDING_CF)
list(APPEND OPENCFLITE_DEF OPENCFLITE_CMAKE)
#list(APPEND OPENCFLITE_DEF "OPENCFLITE_VERSION=${OPENCFLITE_VERSION}")
if ("${OPENCFLITE_LINKAGE}" STREQUAL "SHARED")
    list(APPEND OPENCFLITE_DEF OPENCFLITE_LIBRARY_TYPE_SHARED)
    set(BUILD_SHARED_LIBS ON)
else()
    list(APPEND OPENCFLITE_DEF OPENCFLITE_LIBRARY_TYPE_STATIC)
endif()
if ("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
    list(APPEND OPENCFLITE_DEF OPENCFLITE_DEBUG)
    list(APPEND OPENCFLITE_DEF TEST)
endif()
if ("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang")
    list(APPEND OPENCFLITE_DEF OPENCFLITE_CLANG)
endif()
if ("${UNAME_M}" MATCHES "arm")
    list(APPEND OPENCFLITE_DEF OPENCFLITE_ARM)
endif()
if (APPLE)
    list(APPEND OPENCFLITE_DEF DEPLOYMENT_TARGET_MACOSX)
    list(APPEND OPENCFLITE_DEF OPENCFLITE_OS_APPLE)
elseif (ANDROID)
    list(APPEND OPENCFLITE_DEF OPENCFLITE_OS_ANDROID)
elseif (MINGW OR MSVC)
    list(APPEND OPENCFLITE_DEF DEPLOYMENT_TARGET_WINDOWS)
    list(APPEND OPENCFLITE_DEF OPENCFLITE_OS_WINDOWS)
    if (MINGW)
        list(APPEND OPENCFLITE_DEF OPENCFLITE_MINGW)
    endif()
else()
    list(APPEND OPENCFLITE_DEF DEPLOYMENT_TARGET_LINUX)
    list(APPEND OPENCFLITE_DEF OPENCFLITE_OS_LINUX)
endif()
if ("${CMAKE_SIZEOF_VOID_P}" STREQUAL "4")
    list(APPEND OPENCFLITE_DEF OPENCFLITE_BITNESS_32)
else ()
    list(APPEND OPENCFLITE_DEF OPENCFLITE_BITNESS_64)
endif ()
include(TestBigEndian)
TEST_BIG_ENDIAN(IS_BIG_ENDIAN)
if(IS_BIG_ENDIAN)
    list(APPEND OPENCFLITE_DEF OPENCFLITE_ENDIANNESS_BIG)
else()
    list(APPEND OPENCFLITE_DEF OPENCFLITE_ENDIANNESS_LITTLE)
endif()

include_directories(${CMAKE_CURRENT_LIST_DIR})
#include_directories(${CMAKE_CURRENT_LIST_DIR}/include)
include_directories(${PROJECT_BINARY_DIR})
include_directories(${PROJECT_BINARY_DIR}/CoreFoundation)

if (APPLE AND EXISTS "${SYSROOT}")
    include_directories(${SYSROOT}/usr/include)
endif()

if (MSVC)
    add_subdirectory(${CMAKE_CURRENT_LIST_DIR}/pthreads)
    include_directories(${CMAKE_CURRENT_LIST_DIR}/pthreads)
    include_directories(${PROJECT_BINARY_DIR}/pthreads)
endif()

set(OPENCFLITE_LIB_DEF )
foreach(DEF IN LISTS OPENCFLITE_DEF)
    list(APPEND OPENCFLITE_LIB_DEF ${DEF})
endforeach()
list(APPEND OPENCFLITE_LIB_DEF OPENCFLITE_TARGET_TYPE_LIBRARY)

set(OPENCFLITE_LIB_SRC_OBJC )
set(OPENCFLITE_LIB_SRC )
set(OPENCFLITE_LIB_INC )

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFApplicationPreferences.c)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFArray.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFArray.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFArray.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFBag.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFBag.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFBag.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFBase.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFBase.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFBase.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFBasicHash.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFBasicHash.h)
if (APPLE)
    list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFBasicHash.m)
    #list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFBasicHashFindBucket.m)
    list(APPEND OPENCFLITE_LIB_SRC_OBJC ${CMAKE_CURRENT_LIST_DIR}/CFBasicHash.m)
    list(APPEND OPENCFLITE_LIB_SRC_OBJC ${CMAKE_CURRENT_LIST_DIR}/CFBasicHashFindBucket.m)
else()
    list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFBasicHash.c)
endif()

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFBinaryHeap.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFBinaryHeap.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFBinaryHeap.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFBinaryPList.c)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFBitVector.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFBitVector.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFBitVector.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFBuiltinConverters.c)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFBundle_BinaryTypes.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFBundle_BinaryTypes.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFBundle_Internal.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFBundle_Internal.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFBundle_Resources.c)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFBundle.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFBundle.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFBundle.h)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFBundlePriv.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFBundlePriv.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFByteOrder.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFByteOrder.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFCalendar.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFCalendar.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFCalendar.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFCharacterSet.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFCharacterSet.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFCharacterSet.h)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFCharacterSetPriv.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFCharacterSetPriv.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFConcreteStreams.c)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFData.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFData.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFData.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFDate.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFDate.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFDate.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFDateFormatter.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFDateFormatter.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFDateFormatter.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFDictionary.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFDictionary.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFDictionary.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFError_Private.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFError_Private.h)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFError.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFError.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFError.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFFileDescriptor.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFFileDescriptor.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFFileDescriptor.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFFileUtilities.c)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFICUConverters.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFICUConverters.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFICUConverters.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFLocale.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFLocale.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFLocale.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFLocaleIdentifier.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFLocaleInternal.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFLocaleInternal.h)

if (APPLE)
    list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFLocaleKeys.m)
    list(APPEND OPENCFLITE_LIB_SRC_OBJC ${CMAKE_CURRENT_LIST_DIR}/CFLocaleKeys.m)
else()
    list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFLocaleKeys.c)
endif()

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFLogUtilities.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFLogUtilities.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFMachPort.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFMachPort.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFMachPort.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFMessagePort.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFMessagePort.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFMessagePort.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFNotificationCenter.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFNotificationCenter.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFNotificationCenter.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFNumber.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFNumber.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFNumber.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFNumberFormatter.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFNumberFormatter.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFNumberFormatter.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFPlatform.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFPlatformConverters.c)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFPlugIn_Factory.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFPlugIn_Factory.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFPlugIn_Factory.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFPlugIn_Instance.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFPlugIn_PlugIn.c)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFPlugIn.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFPlugIn.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFPlugIn.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFPlugInCOM.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFPlugInCOM.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFPreferences.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFPreferences.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFPreferences.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFPriv.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFPriv.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFPropertyList.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFPropertyList.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFPropertyList.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFRunLoop.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFRunLoop.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFRunLoop.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFRuntime.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFRuntime.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFRuntime.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFSet.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFSet.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFSet.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFSocket.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFSocket.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFSocket.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFSocketStream.c)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFSortFunctions.c)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFStorage.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFStorage.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFStorage.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFStream.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFStream.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFStream.h)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFStreamAbstract.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFStreamAbstract.h)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFStreamInternal.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFStreamInternal.h)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFStreamPriv.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFStreamPriv.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFString.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFString.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFString.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFStringDefaultEncoding.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFStringDefaultEncoding.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFStringEncodingConverter.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFStringEncodingConverter.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFStringEncodingConverter.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFStringEncodingConverterExt.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFStringEncodingConverterExt.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFStringEncodingConverterPriv.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFStringEncodingConverterPriv.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFStringEncodingDatabase.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFStringEncodingDatabase.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFStringEncodingDatabase.h)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFStringEncodingExt.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFStringEncodingExt.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFStringEncodings.c)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFStringScanner.c)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFStringUtilities.c)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFSystemDirectories.c)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFTimeZone.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFTimeZone.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFTimeZone.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFTree.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFTree.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFTree.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFUniChar.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFUniChar.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFUniChar.h)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFUniCharPriv.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFUniCharPriv.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFUnicodeDecomposition.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFUnicodeDecomposition.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFUnicodeDecomposition.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFUnicodePrecomposition.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFUnicodePrecomposition.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFUnicodePrecomposition.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFURL.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFURL.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFURL.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFURLAccess.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFURLAccess.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFURLAccess.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFURLPriv.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFURLPriv.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFUserNotification.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFUserNotification.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFUserNotification.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFUtilities.c)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFUUID.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFUUID.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFUUID.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFVersion.c)

if (WINDOWS)
    list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFWindowsMessageQueue.c)
    list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFWindowsMessageQueue.h)
    list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFWindowsMessageQueue.h)

    list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFWindowsUtilities.c)
endif()

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFUUID.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFUUID.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFUUID.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFXMLNode.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFXMLNode.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFXMLNode.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFXMLParser.c)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFXMLParser.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CFXMLParser.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFXMLPreferencesDomain.c)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CFXMLTree.c)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CoreFoundation_Prefix.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CoreFoundation_Prefix.h)
list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/CoreFoundation.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/CoreFoundation.h)

list(APPEND OPENCFLITE_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/ForFoundationOnly.h)
list(APPEND OPENCFLITE_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/ForFoundationOnly.h)

#add_custom_command(OUTPUT ${PROJECT_BINARY_DIR}/CoreFoundation COMMAND ${CMAKE_COMMAND} -E make_directory ${PROJECT_BINARY_DIR}/CoreFoundation COMMENT "mkdir -p ${PROJECT_BINARY_DIR}/CoreFoundation" WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR})
foreach(INC IN LISTS OPENCFLITE_LIB_INC)
    get_filename_component(OPENCFLITE_LIB_INC_NAME ${INC} NAME)
    set_source_files_properties(${PROJECT_BINARY_DIR}/CoreFoundation/${OPENCFLITE_LIB_INC_NAME} PROPERTIES GENERATED TRUE)
    list(APPEND OPENCFLITE_LIB_SRC ${PROJECT_BINARY_DIR}/CoreFoundation/${OPENCFLITE_LIB_INC_NAME})
    add_custom_command(OUTPUT ${PROJECT_BINARY_DIR}/CoreFoundation/${OPENCFLITE_LIB_INC_NAME} COMMAND ${CMAKE_COMMAND} -E copy ${CMAKE_CURRENT_LIST_DIR}/${OPENCFLITE_LIB_INC_NAME} ${PROJECT_BINARY_DIR}/CoreFoundation/${OPENCFLITE_LIB_INC_NAME} COMMENT "cp -r ${CMAKE_CURRENT_LIST_DIR}/${OPENCFLITE_LIB_INC_NAME} ${PROJECT_BINARY_DIR}/CoreFoundation/${OPENCFLITE_LIB_INC_NAME}" WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR})
endforeach()
foreach(OBJC IN LISTS OPENCFLITE_LIB_SRC_OBJC)
    set_source_files_properties(${OPENCFLITE_LIB_SRC_OBJC} PROPERTIES COMPILE_FLAGS "-DINCLUDE_OBJC")
endforeach()
add_library(libopencflite ${OPENCFLITE_LINKAGE} ${OPENCFLITE_LIB_SRC})
if ("${OPENCFLITE_LINKAGE}" STREQUAL "SHARED" AND (APPLE OR WINDOWS))
    install(TARGETS libopencflite RUNTIME DESTINATION ${CMAKE_INSTALL_PREFIX}/bin ARCHIVE DESTINATION ${CMAKE_INSTALL_PREFIX}/bin LIBRARY DESTINATION ${CMAKE_INSTALL_PREFIX}/bin FRAMEWORK DESTINATION ${CMAKE_INSTALL_PREFIX}/bin)
else()
    install(TARGETS libopencflite)
endif()
target_compile_features(libopencflite PRIVATE cxx_std_17)
set_target_properties(libopencflite PROPERTIES LINKER_LANGUAGE CXX)
if (MSVC)
    target_link_libraries(libopencflite PRIVATE pthreadVC3)
endif()
target_compile_definitions(libopencflite PRIVATE ${OPENCFLITE_LIB_DEF})
#set_target_properties(libopencflite PROPERTIES PUBLIC_HEADER "${OPENCFLITE_LIB_INC}")
install(FILES ${OPENCFLITE_LIB_INC} DESTINATION ${CMAKE_INSTALL_PREFIX}/include/libopencflite)

set(OPENCFLITE_BIN_DEF )
foreach(DEF IN LISTS OPENCFLITE_DEF)
    list(APPEND OPENCFLITE_BIN_DEF ${DEF})
endforeach()
list(APPEND OPENCFLITE_BIN_DEF OPENCFLITE_TARGET_TYPE_EXECUTABLE)

set(OPENCFLITE_BIN_SRC )

if ("${OPENCFLITE_BINARIES}" STREQUAL "ON")
    add_executable(opencflite ${OPENCFLITE_BIN_SRC})
    add_dependencies(opencflite libopencflite)
    install(TARGETS opencflite RUNTIME DESTINATION ${CMAKE_INSTALL_PREFIX}/bin BUNDLE DESTINATION ${CMAKE_INSTALL_PREFIX}/bin)
    target_compile_features(opencflite PRIVATE cxx_std_17)
    set_target_properties(opencflite PROPERTIES LINKER_LANGUAGE CXX)
    if ("${OPENCFLITE_LINKAGE}" STREQUAL "SHARED")
        target_link_libraries(opencflite PRIVATE libopencflite)
    else()
        target_link_libraries(opencflite PRIVATE libopencflite)
    endif()
    target_compile_definitions(opencflite PRIVATE ${OPENCFLITE_BIN_DEF})
    if (APPLE)
        add_custom_command(TARGET opencflite POST_BUILD COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_INSTALL_PREFIX}/bin COMMENT "Make binary installation" WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR})
        add_custom_command(TARGET opencflite POST_BUILD COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_INSTALL_PREFIX}/lib COMMENT "Make library installation" WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR})
        add_custom_command(TARGET opencflite POST_BUILD COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_INSTALL_PREFIX}/include COMMENT "Make header installation" WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR})
        if ("${CMAKE_GENERATOR}" MATCHES "Xcode" AND "${CMAKE_BUILD_TYPE}" STREQUAL "Debug" AND NOT "${SW_VERS}" STREQUAL "")
            #set_target_properties(opencflite PROPERTIES XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY "Apple Development")
            #set_target_properties(opencflite PROPERTIES XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY "-")
            set_target_properties(opencflite PROPERTIES XCODE_ATTRIBUTE_CODE_SIGN_ENTITLEMENTS ${CMAKE_CURRENT_LIST_DIR}/opencflite.entitlements)
            add_custom_command(TARGET opencflite POST_BUILD COMMAND codesign --entitlements "${CMAKE_CURRENT_LIST_DIR}/opencflite.entitlements" --sign - --force --verbose --timestamp --deep $<TARGET_FILE:opencflite> || :)
            if ("${OPENCFLITE_LINKAGE}" STREQUAL "SHARED")
                add_custom_command(TARGET opencflite POST_BUILD COMMAND codesign --entitlements "${CMAKE_CURRENT_LIST_DIR}/opencflite.entitlements" --sign - --force --verbose --timestamp --deep $<TARGET_FILE:libopencflite> || :)
            endif()
        endif()
        add_custom_command(TARGET opencflite POST_BUILD COMMAND ${CMAKE_INSTALL_NAME_TOOL} -add_rpath "@executable_path/" $<TARGET_FILE:opencflite> || :)
        string(LENGTH "${OPENCFLITE_CODESIGNING}" LEN)
        if ("${LEN}" STREQUAL "40" AND "${CMAKE_BUILD_TYPE}" STREQUAL "Release" AND NOT "${SW_VERS}" STREQUAL "")
            add_custom_command(TARGET opencflite POST_BUILD COMMAND codesign --sign "${OPENCFLITE_CODESIGNING}" --force --verbose --timestamp --deep $<TARGET_FILE:opencflite> || :)
            if ("${OPENCFLITE_LINKAGE}" STREQUAL "SHARED")
                add_custom_command(TARGET opencflite POST_BUILD COMMAND codesign --sign "${OPENCFLITE_CODESIGNING}" --force --verbose --timestamp --deep $<TARGET_FILE:libopencflite> || :)
            endif()
        endif()
    endif()
endif()

